// Code Generated by Sidekick is for learning and experimentation purposes only.
import Papa from 'papaparse';

export function fetchSheetData(sheetCsvUrl) {
  return fetch(sheetCsvUrl)
    .then(res => res.text())
    .then(text => {
      return new Promise((resolve) => {
        Papa.parse(text, {
          header: true,
          skipEmptyLines: true,
          complete: (results) => resolve(results.data),
        });
      });
    });
}
